"""Interactive onboarding for HydroMemory — `hydromem init`.

Writes a project-local ``hydromemory.toml`` (human-readable, source of truth on
re-run) and a sibling ``.env`` (the runtime-consumed ``HYDRO_*`` vars), and
appends managed entries to ``.gitignore``. The TOML and the ``.env`` are kept
in lockstep — the TOML mirrors every value written to ``.env`` so a re-run can
load it back as the new defaults.

Designed to be safe to re-run: existing values become the new defaults,
unrelated ``.env`` keys are preserved untouched, and an existing
``.gitignore`` block is only appended when missing.
"""
from __future__ import annotations

import argparse
import os
import secrets
import sys
import tomllib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

CONFIG_FILENAME = "hydromemory.toml"
ENV_FILENAME = ".env"
GITIGNORE_FILENAME = ".gitignore"

GITIGNORE_BLOCK = """# HydroMemory — generated by `hydromem init`
.env
hydromemory.db
hydromemory.db-journal
.hydromem-vault/
"""

PRESETS: dict[str, dict[str, Any]] = {
    "offline": {
        "intelligence_backend": "stub",
        "embedding_backend": "stub",
        "vector_backend": "brute",
        "vault_enabled": False,
    },
    "claude": {
        "intelligence_backend": "claude",
        "embedding_backend": "claude",
        "vector_backend": "brute",
        "vault_enabled": False,
    },
    "team": {
        "intelligence_backend": "stub",
        "embedding_backend": "local",
        "vector_backend": "ann",
        "vault_enabled": True,
    },
}


@dataclass
class InitAnswers:
    """The full set of values the wizard captures. Defaults match a fresh
    offline install — same shape ``HydroConfig`` documents."""

    project_name: str = "hydromemory"
    # storage
    storage_backend: str = "sqlite"  # only shipped backend; "postgres" reserved
    db_path: str = "./hydromemory.db"
    # vectors / embeddings
    vector_backend: str = "brute"
    vector_dim: int = 256
    embedding_backend: str = "stub"
    # intelligence
    intelligence_backend: str = "stub"
    anthropic_api_key: str = ""
    claude_model: str = "claude-opus-4-7"
    # vault
    vault_enabled: bool = False
    vault_key: str = ""
    # identity (default permission scope for absorbs/recalls when no flag is passed)
    default_agent: str = "assistant"
    default_trust: str = "approved"
    default_reservoir: str = "working_stream"
    # cycle
    cycle_tick_seconds: float = 1.0

    extras_to_install: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# I/O — TOML, .env, .gitignore
# ---------------------------------------------------------------------------


def _toml_scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return repr(value)
    if isinstance(value, list):
        return "[" + ", ".join(_toml_scalar(v) for v in value) + "]"
    s = str(value)
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _render_toml(answers: InitAnswers) -> str:
    sections: list[tuple[str, list[tuple[str, Any]]]] = [
        ("project", [("name", answers.project_name)]),
        (
            "storage",
            [("backend", answers.storage_backend), ("db_path", answers.db_path)],
        ),
        (
            "vectors",
            [
                ("backend", answers.vector_backend),
                ("dim", answers.vector_dim),
                ("source", answers.embedding_backend),
            ],
        ),
        (
            "intelligence",
            [
                ("backend", answers.intelligence_backend),
                ("claude_model", answers.claude_model),
            ],
        ),
        ("vault", [("enabled", answers.vault_enabled)]),
        (
            "identity",
            [
                ("default_agent", answers.default_agent),
                ("default_trust", answers.default_trust),
                ("default_reservoir", answers.default_reservoir),
            ],
        ),
        ("cycle", [("tick_seconds", answers.cycle_tick_seconds)]),
    ]
    out = [
        "# HydroMemory configuration — generated by `hydromem init`.",
        "# Re-running `hydromem init` reads this file and uses these values as defaults.",
        "# Secrets (vault key, ANTHROPIC_API_KEY) live in .env, never here.",
        "",
    ]
    for name, items in sections:
        out.append(f"[{name}]")
        for k, v in items:
            out.append(f"{k} = {_toml_scalar(v)}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def load_toml_defaults(path: Path) -> InitAnswers:
    """Load ``hydromemory.toml`` into an ``InitAnswers``. Missing keys keep
    their dataclass defaults so a partial file still round-trips."""

    answers = InitAnswers()
    if not path.exists():
        return answers
    data = tomllib.loads(path.read_text())
    answers.project_name = data.get("project", {}).get("name", answers.project_name)
    storage = data.get("storage", {})
    answers.storage_backend = storage.get("backend", answers.storage_backend)
    answers.db_path = storage.get("db_path", answers.db_path)
    vectors = data.get("vectors", {})
    answers.vector_backend = vectors.get("backend", answers.vector_backend)
    answers.vector_dim = int(vectors.get("dim", answers.vector_dim))
    answers.embedding_backend = vectors.get("source", answers.embedding_backend)
    intel = data.get("intelligence", {})
    answers.intelligence_backend = intel.get("backend", answers.intelligence_backend)
    answers.claude_model = intel.get("claude_model", answers.claude_model)
    answers.vault_enabled = bool(data.get("vault", {}).get("enabled", answers.vault_enabled))
    identity = data.get("identity", {})
    answers.default_agent = identity.get("default_agent", answers.default_agent)
    answers.default_trust = identity.get("default_trust", answers.default_trust)
    answers.default_reservoir = identity.get("default_reservoir", answers.default_reservoir)
    answers.cycle_tick_seconds = float(
        data.get("cycle", {}).get("tick_seconds", answers.cycle_tick_seconds)
    )
    return answers


def _env_pairs(answers: InitAnswers) -> list[tuple[str, str]]:
    """The ``.env`` projection of an answer set. Keep keys ASCII and shell-safe."""

    pairs: list[tuple[str, str]] = [
        ("HYDRO_DB_PATH", answers.db_path),
        ("HYDRO_VECTOR_BACKEND", answers.vector_backend),
        ("HYDRO_EMBED_DIM", str(answers.vector_dim)),
        ("HYDRO_EMBEDDING_BACKEND", answers.embedding_backend),
        ("HYDRO_INTELLIGENCE_BACKEND", answers.intelligence_backend),
        ("HYDRO_CLAUDE_MODEL", answers.claude_model),
        ("HYDRO_VAULT_ENABLED", "true" if answers.vault_enabled else "false"),
        ("HYDRO_DEFAULT_AGENT", answers.default_agent),
        ("HYDRO_DEFAULT_TRUST", answers.default_trust),
        ("HYDRO_DEFAULT_RESERVOIR", answers.default_reservoir),
        ("HYDRO_CYCLE_TICK_SECONDS", str(answers.cycle_tick_seconds)),
    ]
    if answers.intelligence_backend == "claude" or answers.anthropic_api_key:
        pairs.append(("ANTHROPIC_API_KEY", answers.anthropic_api_key))
    if answers.vault_enabled or answers.vault_key:
        pairs.append(("HYDRO_VAULT_KEY", answers.vault_key))
    return pairs


def _quote_env(value: str) -> str:
    if value == "":
        return ""
    needs_quote = any(c in value for c in ' \t#"\'$`\\') or value != value.strip()
    if not needs_quote:
        return value
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def merge_env(existing_text: str, pairs: list[tuple[str, str]]) -> str:
    """Update or append each ``KEY=VALUE`` in the existing ``.env`` text,
    preserving unrelated lines and order. New keys are appended below an
    explanatory marker comment if none of the keys are present yet."""

    lines = existing_text.splitlines() if existing_text else []
    keys_in_pairs = {k for k, _ in pairs}
    seen: set[str] = set()
    out: list[str] = []
    for line in lines:
        stripped = line.lstrip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            out.append(line)
            continue
        key = stripped.split("=", 1)[0].strip()
        if key in keys_in_pairs:
            new_value = next(v for k, v in pairs if k == key)
            out.append(f"{key}={_quote_env(new_value)}")
            seen.add(key)
        else:
            out.append(line)
    appended = [(k, v) for k, v in pairs if k not in seen]
    if appended:
        if out and out[-1].strip() != "":
            out.append("")
        out.append("# HydroMemory — generated by `hydromem init`")
        for k, v in appended:
            out.append(f"{k}={_quote_env(v)}")
    return "\n".join(out).rstrip() + "\n"


def merge_gitignore(existing_text: str) -> str:
    """Append the HydroMemory ignore block if the marker isn't already there."""

    marker = "# HydroMemory — generated by `hydromem init`"
    if marker in (existing_text or ""):
        return existing_text if existing_text.endswith("\n") else existing_text + "\n"
    base = (existing_text or "").rstrip()
    sep = "\n\n" if base else ""
    return base + sep + GITIGNORE_BLOCK


# ---------------------------------------------------------------------------
# Prompting
# ---------------------------------------------------------------------------


def _ask(
    prompt: str,
    default: str,
    *,
    choices: list[str] | None = None,
    stream_in,
    stream_out,
    non_interactive: bool,
) -> str:
    if non_interactive:
        return default
    suffix = f" [{default}]" if default else ""
    if choices:
        suffix = f" ({'/'.join(choices)}) [{default}]"
    stream_out.write(f"{prompt}{suffix}: ")
    stream_out.flush()
    raw = stream_in.readline()
    if raw == "":
        return default
    value = raw.strip()
    if value == "":
        return default
    if choices and value not in choices:
        stream_out.write(f"  (must be one of {', '.join(choices)} — using {default})\n")
        return default
    return value


def _ask_bool(
    prompt: str, default: bool, *, stream_in, stream_out, non_interactive: bool
) -> bool:
    default_str = "y" if default else "n"
    raw = _ask(
        prompt,
        default_str,
        choices=["y", "n"],
        stream_in=stream_in,
        stream_out=stream_out,
        non_interactive=non_interactive,
    )
    return raw.lower().startswith("y")


# ---------------------------------------------------------------------------
# Wizard
# ---------------------------------------------------------------------------


def run_wizard(
    *,
    cwd: Path,
    force: bool = False,
    non_interactive: bool = False,
    preset: str | None = None,
    smoke_test: bool = True,
    stream_in=None,
    stream_out=None,
) -> int:
    """Run the wizard inside ``cwd``. Returns a process exit code.

    The wizard is deterministic given (`cwd`, `stream_in`, `preset`,
    `non_interactive`), which keeps it testable end-to-end without monkeying
    with the global terminal.
    """

    stream_in = stream_in if stream_in is not None else sys.stdin
    stream_out = stream_out if stream_out is not None else sys.stdout

    toml_path = cwd / CONFIG_FILENAME
    env_path = cwd / ENV_FILENAME
    gitignore_path = cwd / GITIGNORE_FILENAME

    defaults = load_toml_defaults(toml_path)
    if preset:
        if preset not in PRESETS:
            stream_out.write(f"error: unknown preset {preset!r}; choose from {sorted(PRESETS)}\n")
            return 2
        for k, v in PRESETS[preset].items():
            setattr(defaults, k, v)

    existed = toml_path.exists()
    if existed and not force and not non_interactive:
        stream_out.write(
            f"Found existing {CONFIG_FILENAME}. Re-running will use its values as defaults.\n"
            "Press Ctrl-C to abort, or enter to continue.\n"
        )
        # The continue-prompt reads one line so a piped test can opt past it.
        stream_in.readline()

    stream_out.write("\nHydroMemory init — droplet engine setup\n\n")

    answers = InitAnswers(**{k: getattr(defaults, k) for k in InitAnswers.__dataclass_fields__})

    # 1. Project name
    answers.project_name = _ask(
        "Project name",
        defaults.project_name,
        stream_in=stream_in,
        stream_out=stream_out,
        non_interactive=non_interactive,
    )

    # 2. Storage
    stream_out.write(
        "\nWhere should droplets live?\n"
        "  sqlite              local file (default, only shipped backend)\n"
        "  postgres            pgvector — experimental, not yet implemented\n"
    )
    answers.storage_backend = _ask(
        "Backend",
        defaults.storage_backend,
        choices=["sqlite", "postgres"],
        stream_in=stream_in,
        stream_out=stream_out,
        non_interactive=non_interactive,
    )
    if answers.storage_backend == "postgres":
        stream_out.write(
            "  note: postgres backend is reserved but not implemented; "
            "falling back to sqlite for now.\n"
        )
        answers.storage_backend = "sqlite"
    answers.db_path = _ask(
        "SQLite path",
        defaults.db_path,
        stream_in=stream_in,
        stream_out=stream_out,
        non_interactive=non_interactive,
    )

    # 3. Intelligence backend
    stream_out.write(
        "\nIntelligence backend (text ops, summaries, classifiers):\n"
        "  stub                deterministic, offline, no key (recommended)\n"
        "  claude              uses ANTHROPIC_API_KEY\n"
    )
    answers.intelligence_backend = _ask(
        "Backend",
        defaults.intelligence_backend,
        choices=["stub", "claude"],
        stream_in=stream_in,
        stream_out=stream_out,
        non_interactive=non_interactive,
    )
    if answers.intelligence_backend == "claude":
        env_key = os.environ.get("ANTHROPIC_API_KEY", "")
        prompt_default = env_key or defaults.anthropic_api_key or "(skip — set later)"
        raw = _ask(
            "ANTHROPIC_API_KEY (enter to skip)",
            prompt_default,
            stream_in=stream_in,
            stream_out=stream_out,
            non_interactive=non_interactive,
        )
        answers.anthropic_api_key = "" if raw == prompt_default and raw.startswith("(skip") else raw

    # 4. Embeddings
    stream_out.write(
        "\nEmbeddings:\n"
        "  stub                deterministic vectors (dim=256)\n"
        "  local               MiniLM (installs `.[local]`, dim=384, offline)\n"
        "  claude              uses ANTHROPIC_API_KEY\n"
    )
    answers.embedding_backend = _ask(
        "Embedding source",
        defaults.embedding_backend,
        choices=["stub", "local", "claude"],
        stream_in=stream_in,
        stream_out=stream_out,
        non_interactive=non_interactive,
    )
    if answers.embedding_backend == "local":
        answers.vector_dim = 384
        answers.extras_to_install.append("local")
    elif answers.embedding_backend == "stub":
        answers.vector_dim = 256

    # 5. Vector index
    stream_out.write(
        "\nVector index:\n"
        "  brute               exact, fine up to ~50k droplets\n"
        "  ann                 hnswlib (installs `.[ann]`)\n"
    )
    answers.vector_backend = _ask(
        "Index",
        defaults.vector_backend,
        choices=["brute", "ann"],
        stream_in=stream_in,
        stream_out=stream_out,
        non_interactive=non_interactive,
    )
    if answers.vector_backend == "ann":
        answers.extras_to_install.append("ann")

    # 6. Vault
    answers.vault_enabled = _ask_bool(
        "\nEnable encrypted user vault?",
        defaults.vault_enabled,
        stream_in=stream_in,
        stream_out=stream_out,
        non_interactive=non_interactive,
    )
    if answers.vault_enabled:
        generate = _ask_bool(
            "  generate a passphrase?",
            True,
            stream_in=stream_in,
            stream_out=stream_out,
            non_interactive=non_interactive,
        )
        if generate:
            answers.vault_key = secrets.token_urlsafe(32)
            stream_out.write(
                "  generated vault key (will be written to .env — keep it safe):\n"
                f"    {answers.vault_key}\n"
            )
        else:
            answers.vault_key = _ask(
                "  paste vault passphrase",
                "",
                stream_in=stream_in,
                stream_out=stream_out,
                non_interactive=non_interactive,
            )

    # 7. Identity / permission default scope
    stream_out.write("\nDefault identity (used when absorb/recall is called without flags):\n")
    answers.default_agent = _ask(
        "  agent name",
        defaults.default_agent,
        stream_in=stream_in,
        stream_out=stream_out,
        non_interactive=non_interactive,
    )
    answers.default_trust = _ask(
        "  trust level",
        defaults.default_trust,
        choices=["session", "approved", "high_trust"],
        stream_in=stream_in,
        stream_out=stream_out,
        non_interactive=non_interactive,
    )
    answers.default_reservoir = _ask(
        "  default reservoir for new droplets",
        defaults.default_reservoir,
        choices=["working_stream", "surface", "groundwater", "glacier"],
        stream_in=stream_in,
        stream_out=stream_out,
        non_interactive=non_interactive,
    )

    # 8. Cycle tick
    cycle_raw = _ask(
        "\nCycle tick interval (seconds)",
        str(defaults.cycle_tick_seconds),
        stream_in=stream_in,
        stream_out=stream_out,
        non_interactive=non_interactive,
    )
    try:
        answers.cycle_tick_seconds = float(cycle_raw)
    except ValueError:
        stream_out.write(
            f"  invalid number {cycle_raw!r}, using {defaults.cycle_tick_seconds}\n"
        )
        answers.cycle_tick_seconds = defaults.cycle_tick_seconds

    # ----------------- write -----------------
    toml_text = _render_toml(answers)
    toml_path.write_text(toml_text)
    stream_out.write(f"\n  wrote {toml_path.name}\n")

    env_existing = env_path.read_text() if env_path.exists() else ""
    env_text = merge_env(env_existing, _env_pairs(answers))
    env_path.write_text(env_text)
    try:
        env_path.chmod(0o600)
    except OSError:
        pass
    stream_out.write(f"  wrote {env_path.name} (chmod 600)\n")

    gi_existing = gitignore_path.read_text() if gitignore_path.exists() else ""
    gi_text = merge_gitignore(gi_existing)
    if gi_text != gi_existing:
        gitignore_path.write_text(gi_text)
        stream_out.write(f"  updated {gitignore_path.name}\n")

    if answers.extras_to_install:
        extras = ",".join(sorted(set(answers.extras_to_install)))
        stream_out.write(
            f"\nThis configuration needs extras: pip install -e '.[{extras}]'\n"
        )

    if smoke_test:
        stream_out.write("\nSmoke test: running example A in an in-memory engine...\n")
        try:
            from hydromemory.examples import run_example

            result = run_example("A")
            facts = len(result) if isinstance(result, dict) else "?"
            stream_out.write(f"  ok ({facts} fact(s))\n")
        except Exception as exc:  # pragma: no cover - defensive
            stream_out.write(f"  smoke test failed: {exc}\n")

    stream_out.write(
        "\nNext:\n"
        "  hydromem run-example A\n"
        "  hydromem absorb --content 'my first droplet' --source conversation\n"
        "  hydromem recall 'first droplet'\n"
    )
    return 0


def add_init_subparser(sub: argparse._SubParsersAction) -> None:
    p = sub.add_parser("init", help="interactive setup wizard (writes hydromemory.toml + .env)")
    p.add_argument("--force", action="store_true", help="re-ask every step even if hydromemory.toml exists")
    p.add_argument(
        "--non-interactive",
        action="store_true",
        help="take all defaults (or preset values) without prompting",
    )
    p.add_argument("--preset", choices=sorted(PRESETS), help="apply a preset before prompting")
    p.add_argument(
        "--no-smoke-test",
        action="store_true",
        help="skip the post-init run_example('A') smoke test",
    )


def run_init_cli(args: argparse.Namespace) -> int:
    return run_wizard(
        cwd=Path.cwd(),
        force=getattr(args, "force", False),
        non_interactive=getattr(args, "non_interactive", False),
        preset=getattr(args, "preset", None),
        smoke_test=not getattr(args, "no_smoke_test", False),
    )
